_linux_x86_64 = [
    "@platforms//os:linux",
    "@platforms//cpu:x86_64",
]

_linux_arm64 = [
    "@platforms//os:linux",
    "@platforms//cpu:arm64",
]

platform(
    name = "linux_x86_64",
    constraint_values = _linux_x86_64,
    visibility = ["//visibility:public"],
)

platform(
    name = "linux_arm64",
    constraint_values = _linux_arm64,
    visibility = ["//visibility:public"],
)
