"rules_pycross_oci"

bazel_dep(name = "aspect_bazel_lib", version = "2.21.2")
bazel_dep(name = "aspect_rules_py", version = "1.11.7")
bazel_dep(name = "hermetic_cc_toolchain", version = "3.1.0")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pycross", version = "2.0.0-alpha.1")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "tar.bzl", version = "0.10.5")

# git_override(
#     module_name = "rules_pycross",
#     remote = "https://github.com/jvolkman/rules_pycross.git",
#     commit = "094c6df40072b6ed4ab1d81cd7e8ccfe1b62714c"
# )

toolchains = use_extension("@hermetic_cc_toolchain//toolchain:ext.bzl", "toolchains")
use_repo(toolchains, "zig_sdk")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "ubuntu_24_04",
    digest = "sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee",
    image = "ubuntu",
    platforms = [
        "linux/arm64/v8",
        "linux/amd64",
    ],
)
use_repo(oci, "ubuntu_24_04")
oci.pull(
    name = "openjdk_17",
    digest = "sha256:d8df9373d3d9a5c9b3558575c2f7340fddaa8eee93f1b0841c51ca5f20293600",
    # tag = "17-ubuntu",
    image = "mcr.microsoft.com/openjdk/jdk",
    platforms = [
        "linux/arm64",
        "linux/amd64",
    ],
)
use_repo(oci, "openjdk_17", "openjdk_17_linux_amd64", "openjdk_17_linux_arm64", "ubuntu_24_04_linux_amd64", "ubuntu_24_04_linux_arm64_v8")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.14.0",
)
python.toolchain(python_version = "3.10.6")
use_repo(python, "python_versions")

uv = use_extension("@rules_pycross//pycross/extensions:uv.bzl", "uv")
uv.workspace(
    name = "cowapp_pypi",
    lock_file = "//cowapp:uv.lock",
)
use_repo(uv, "cowapp_pypi")
uv.workspace(
    name = "airflowapp_pypi",
    lock_file = "//airflowapp:uv.lock",
)
use_repo(uv, "airflowapp_pypi")
uv.workspace(
    name = "sparkapp_pypi",
    lock_file = "//sparkapp:uv.lock",
)
uv.repo(
    dependency_groups = ["*"],
    workspace = "sparkapp_pypi",
)
use_repo(uv, "sparkapp_pypi")
uv.workspace(
    name = "torchapp_pypi",
    lock_file = "//torchapp:uv.lock",
)
use_repo(uv, "torchapp_pypi")
