load("@airflowapp_pypi//:requirements.bzl", "requirement")
load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")
load("@tar.bzl//:tar.bzl", "mutate", "tar")

py_binary(
    name = "airflowapp",
    srcs = [
        "__init__.py",
        "main.py",
    ],
    main = "main.py",
    python_version = "3.10.6",
    deps = [
        requirement("apache-airflow"),
    ],
)

tar(
    name = "airflowapp_files",
    srcs = [
        ":airflowapp",
    ],
    mutate = mutate(
        strip_prefix = package_name(),
    ),
)

oci_image(
    name = "image",
    base = "@ubuntu_24_04",
    entrypoint = ["/airflowapp"],
    tars = [
        ":airflowapp_files",
    ],
)

platform_transition_filegroup(
    name = "image_linux_x86_64",
    srcs = [
        ":image",
    ],
    target_platform = "//:linux_x86_64",
)

platform_transition_filegroup(
    name = "image_linux_arm64",
    srcs = [
        ":image",
    ],
    target_platform = "//:linux_arm64",
)

oci_load(
    name = "tarball_linux_x86_64",
    image = ":image_linux_x86_64",
    repo_tags = [
        "bazel/airflowapp_linux_x86_64:latest",
    ],
)

oci_load(
    name = "tarball_linux_arm64",
    image = ":image_linux_arm64",
    repo_tags = [
        "bazel/airflowapp_linux_arm64:latest",
    ],
)
