load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_test")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")
load("@sparkapp_pypi//:requirements.bzl", "requirement")
load("@tar.bzl//:tar.bzl", "mutate", "tar")

py_binary(
    name = "sparkapp",
    srcs = [
        "__init__.py",
        "main.py",
    ],
    main = "main.py",
    python_version = "3.10.6",
    deps = [
        requirement("pyspark"),
    ],
)

py_test(
    name = "sparkapp_test",
    srcs = glob([
        "tests/*.py",
    ]),
    pytest_main = True,
    python_version = "3.10.6",
    deps = [
        ":sparkapp",
        requirement("pyspark"),
        requirement("pytest"),
    ],
)

tar(
    name = "sparkapp_files",
    srcs = [
        ":sparkapp",
    ],
    mutate = mutate(
        strip_prefix = package_name(),
    ),
)

oci_image(
    name = "image",
    base = "@openjdk_17",
    entrypoint = ["/sparkapp"],
    tars = [
        ":sparkapp_files",
    ],
)

platform_transition_filegroup(
    name = "image_linux_x86_64",
    srcs = [
        ":image",
    ],
    target_platform = "//:linux_x86_64",
)

platform_transition_filegroup(
    name = "image_linux_arm64",
    srcs = [
        ":image",
    ],
    target_platform = "//:linux_arm64",
)

oci_load(
    name = "tarball_linux_x86_64",
    image = ":image_linux_x86_64",
    repo_tags = [
        "bazel/sparkapp_linux_x86_64:latest",
    ],
)

oci_load(
    name = "tarball_linux_arm64",
    image = ":image_linux_arm64",
    repo_tags = [
        "bazel/sparkapp_linux_arm64:latest",
    ],
)
