# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@@rules_pycross~//pycross:defs.bzl", "pycross_wheel_library", "pypi_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

PINS = {
    "cowsay": "cowsay@6.1",
    "numpy": "numpy@2.0.1",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_3_12_darwin_arm64",
        constraint_values = [
            "@@platforms//os:osx",
            "@@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_3_12_linux_arm64",
        constraint_values = [
            "@@platforms//os:linux",
            "@@platforms//cpu:aarch64",
        ],
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_3_12_darwin_arm64": "@@_main//:python_3_12_darwin_arm64",
        ":_env_python_3_12_linux_arm64": "@@_main//:python_3_12_linux_arm64",
    })

    native.alias(
        name = "_wheel_cowsay@6.1",
        actual = "@poetry_wheel_cowsay_6.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "cowsay@6.1",
        wheel = ":_wheel_cowsay@6.1",
    )

    native.alias(
        name = "_wheel_numpy@2.0.1",
        actual = select({
            ":_env_python_3_12_darwin_arm64": "@poetry_wheel_numpy_2.0.1_cp312_cp312_macosx_11_0_arm64//file",
            ":_env_python_3_12_linux_arm64": "@poetry_wheel_numpy_2.0.1_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
        }),
    )

    pycross_wheel_library(
        name = "numpy@2.0.1",
        wheel = ":_wheel_numpy@2.0.1",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        pypi_file,
        name = "poetry_wheel_cowsay_6.1_py3_none_any",
        package_name = "cowsay",
        package_version = "6.1",
        filename = "cowsay-6.1-py3-none-any.whl",
        sha256 = "274b1e6fc1b966d53976333eb90ac94cb07a450a700b455af9fbdf882244b30a",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_numpy_2.0.1_cp312_cp312_macosx_11_0_arm64",
        package_name = "numpy",
        package_version = "2.0.1",
        filename = "numpy-2.0.1-cp312-cp312-macosx_11_0_arm64.whl",
        sha256 = "7d6fddc5fe258d3328cd8e3d7d3e02234c5d70e01ebe377a6ab92adb14039cb4",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_numpy_2.0.1_cp312_cp312_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "numpy",
        package_version = "2.0.1",
        filename = "numpy-2.0.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "529af13c5f4b7a932fb0e1911d3a75da204eff023ee5e0e79c1751564221a5c8",
    )
