# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "cowsay": "cowsay@6.1",
    "meson-python": "meson-python@0.13.1",
    "numpy": "numpy@1.26.4",
    "pyspark": "pyspark@3.5.3",
    "setuptools": "setuptools@68.2.2",
    "wheel": "wheel@0.41.3",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_arm64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_darwin_arm64": "@__main__//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@__main__//:python_darwin_x86_64",
        ":_env_python_linux_arm64": "@__main__//:python_linux_arm64",
        ":_env_python_linux_x86_64": "@__main__//:python_linux_x86_64",
    })

    native.alias(
        name = "_wheel_cowsay@6.1",
        actual = "@poetry_wheel_cowsay_6.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "cowsay@6.1",
        wheel = ":_wheel_cowsay@6.1",
    )

    native.alias(
        name = "_wheel_meson@1.6.0",
        actual = "@poetry_wheel_meson_1.6.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "meson@1.6.0",
        wheel = ":_wheel_meson@1.6.0",
    )

    _meson_python_0_13_1_deps = [
        ":meson@1.6.0",
        ":pyproject-metadata@0.9.0",
        ":tomli@2.2.1",
    ]

    native.alias(
        name = "_wheel_meson-python@0.13.1",
        actual = "@poetry_wheel_meson_python_0.13.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "meson-python@0.13.1",
        deps = _meson_python_0_13_1_deps,
        wheel = ":_wheel_meson-python@0.13.1",
    )

    native.alias(
        name = "_sdist_numpy@1.26.4",
        actual = "@poetry_sdist_numpy_1.26.4//file",
    )

    pycross_wheel_build(
        name = "_build_numpy@1.26.4",
        sdist = ":_sdist_numpy@1.26.4",
        target_environment = _target,
        tags = ["manual"],
    )

    native.alias(
        name = "_wheel_numpy@1.26.4",
        actual = ":_build_numpy@1.26.4",
    )

    pycross_wheel_library(
        name = "numpy@1.26.4",
        wheel = ":_wheel_numpy@1.26.4",
    )

    native.alias(
        name = "_wheel_packaging@24.2",
        actual = "@poetry_wheel_packaging_24.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging@24.2",
        wheel = ":_wheel_packaging@24.2",
    )

    native.alias(
        name = "_wheel_py4j@0.10.9.7",
        actual = "@poetry_wheel_py4j_0.10.9.7_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "py4j@0.10.9.7",
        wheel = ":_wheel_py4j@0.10.9.7",
    )

    _pyproject_metadata_0_9_0_deps = [
        ":packaging@24.2",
    ]

    native.alias(
        name = "_wheel_pyproject-metadata@0.9.0",
        actual = "@poetry_wheel_pyproject_metadata_0.9.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyproject-metadata@0.9.0",
        deps = _pyproject_metadata_0_9_0_deps,
        wheel = ":_wheel_pyproject-metadata@0.9.0",
    )

    _pyspark_3_5_3_deps = [
        ":py4j@0.10.9.7",
    ]

    native.alias(
        name = "_sdist_pyspark@3.5.3",
        actual = "@poetry_sdist_pyspark_3.5.3//file",
    )

    _pyspark_3_5_3_build_deps = [
        ":meson-python@0.13.1",
        ":setuptools@68.2.2",
        ":wheel@0.41.3",
    ]

    pycross_wheel_build(
        name = "_build_pyspark@3.5.3",
        sdist = ":_sdist_pyspark@3.5.3",
        target_environment = _target,
        deps = _pyspark_3_5_3_deps + _pyspark_3_5_3_build_deps,
        tags = ["manual"],
    )

    native.alias(
        name = "_wheel_pyspark@3.5.3",
        actual = ":_build_pyspark@3.5.3",
    )

    pycross_wheel_library(
        name = "pyspark@3.5.3",
        deps = _pyspark_3_5_3_deps,
        wheel = ":_wheel_pyspark@3.5.3",
    )

    native.alias(
        name = "_wheel_setuptools@68.2.2",
        actual = "@poetry_wheel_setuptools_68.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "setuptools@68.2.2",
        wheel = ":_wheel_setuptools@68.2.2",
    )

    native.alias(
        name = "_wheel_tomli@2.2.1",
        actual = "@poetry_wheel_tomli_2.2.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli@2.2.1",
        wheel = ":_wheel_tomli@2.2.1",
    )

    native.alias(
        name = "_wheel_wheel@0.41.3",
        actual = "@poetry_wheel_wheel_0.41.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel@0.41.3",
        wheel = ":_wheel_wheel@0.41.3",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        pypi_file,
        name = "poetry_sdist_numpy_1.26.4",
        package_name = "numpy",
        package_version = "1.26.4",
        filename = "numpy-1.26.4.tar.gz",
        sha256 = "2a02aba9ed12e4ac4eb3ea9421c420301a0c6460d9830d74a9df87efa4912010",
    )

    maybe(
        pypi_file,
        name = "poetry_sdist_pyspark_3.5.3",
        package_name = "pyspark",
        package_version = "3.5.3",
        filename = "pyspark-3.5.3.tar.gz",
        sha256 = "68b7cc0c0c570a7d8644f49f40d2da8709b01d30c9126cc8cf93b4f84f3d9747",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_cowsay_6.1_py3_none_any",
        package_name = "cowsay",
        package_version = "6.1",
        filename = "cowsay-6.1-py3-none-any.whl",
        sha256 = "274b1e6fc1b966d53976333eb90ac94cb07a450a700b455af9fbdf882244b30a",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_meson_1.6.0_py3_none_any",
        package_name = "meson",
        package_version = "1.6.0",
        filename = "meson-1.6.0-py3-none-any.whl",
        sha256 = "234a45f9206c6ee33b473ec1baaef359d20c0b89a71871d58c65a6db6d98fe74",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_meson_python_0.13.1_py3_none_any",
        package_name = "meson-python",
        package_version = "0.13.1",
        filename = "meson_python-0.13.1-py3-none-any.whl",
        sha256 = "e33ea3efbadecc15768c205d03b905c7b3bf72afae1e1ebd84b438c4a3ed3393",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_packaging_24.2_py3_none_any",
        package_name = "packaging",
        package_version = "24.2",
        filename = "packaging-24.2-py3-none-any.whl",
        sha256 = "09abb1bccd265c01f4a3aa3f7a7db064b36514d2cba19a2f694fe6150451a759",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_py4j_0.10.9.7_py2.py3_none_any",
        package_name = "py4j",
        package_version = "0.10.9.7",
        filename = "py4j-0.10.9.7-py2.py3-none-any.whl",
        sha256 = "85defdfd2b2376eb3abf5ca6474b51ab7e0de341c75a02f46dc9b5976f5a5c1b",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_pyproject_metadata_0.9.0_py3_none_any",
        package_name = "pyproject-metadata",
        package_version = "0.9.0",
        filename = "pyproject_metadata-0.9.0-py3-none-any.whl",
        sha256 = "fc862aab066a2e87734333293b0af5845fe8ac6cb69c451a41551001e923be0b",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_setuptools_68.2.2_py3_none_any",
        package_name = "setuptools",
        package_version = "68.2.2",
        filename = "setuptools-68.2.2-py3-none-any.whl",
        sha256 = "b454a35605876da60632df1a60f736524eb73cc47bbc9f3f1ef1b644de74fd2a",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_tomli_2.2.1_py3_none_any",
        package_name = "tomli",
        package_version = "2.2.1",
        filename = "tomli-2.2.1-py3-none-any.whl",
        sha256 = "cb55c73c5f4408779d0cf3eef9f762b9c9f147a77de7b258bef0a5628adc85cc",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_wheel_0.41.3_py3_none_any",
        package_name = "wheel",
        package_version = "0.41.3",
        filename = "wheel-0.41.3-py3-none-any.whl",
        sha256 = "488609bc63a29322326e05560731bf7bfea8e48ad646e1f5e40d366607de0942",
    )
