# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "cowsay": "cowsay@6.1",
    "meson-python": "meson-python@0.16.0",
    "numpy": "numpy@2.1.1",
    "pyspark": "pyspark@3.5.2",
    "setuptools": "setuptools@75.1.0",
    "wheel": "wheel@0.44.0",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_arm64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_darwin_arm64": "@__main__//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@__main__//:python_darwin_x86_64",
        ":_env_python_linux_arm64": "@__main__//:python_linux_arm64",
        ":_env_python_linux_x86_64": "@__main__//:python_linux_x86_64",
    })

    native.alias(
        name = "_wheel_cowsay@6.1",
        actual = "@poetry_wheel_cowsay_6.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "cowsay@6.1",
        wheel = ":_wheel_cowsay@6.1",
    )

    native.alias(
        name = "_wheel_meson@1.5.2",
        actual = "@poetry_wheel_meson_1.5.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "meson@1.5.2",
        wheel = ":_wheel_meson@1.5.2",
    )

    _meson_python_0_16_0_deps = [
        ":meson@1.5.2",
        ":packaging@24.1",
        ":pyproject-metadata@0.8.0",
        ":tomli@2.0.1",
    ]

    native.alias(
        name = "_wheel_meson-python@0.16.0",
        actual = "@poetry_wheel_meson_python_0.16.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "meson-python@0.16.0",
        deps = _meson_python_0_16_0_deps,
        wheel = ":_wheel_meson-python@0.16.0",
    )

    native.alias(
        name = "_sdist_numpy@2.1.1",
        actual = "@poetry_sdist_numpy_2.1.1//file",
    )

    pycross_wheel_build(
        name = "_build_numpy@2.1.1",
        sdist = ":_sdist_numpy@2.1.1",
        target_environment = _target,
        tags = ["manual"],
    )

    native.alias(
        name = "_wheel_numpy@2.1.1",
        actual = ":_build_numpy@2.1.1",
    )

    pycross_wheel_library(
        name = "numpy@2.1.1",
        wheel = ":_wheel_numpy@2.1.1",
    )

    native.alias(
        name = "_wheel_packaging@24.1",
        actual = "@poetry_wheel_packaging_24.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging@24.1",
        wheel = ":_wheel_packaging@24.1",
    )

    native.alias(
        name = "_wheel_py4j@0.10.9.7",
        actual = "@poetry_wheel_py4j_0.10.9.7_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "py4j@0.10.9.7",
        wheel = ":_wheel_py4j@0.10.9.7",
    )

    _pyproject_metadata_0_8_0_deps = [
        ":packaging@24.1",
    ]

    native.alias(
        name = "_wheel_pyproject-metadata@0.8.0",
        actual = "@poetry_wheel_pyproject_metadata_0.8.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyproject-metadata@0.8.0",
        deps = _pyproject_metadata_0_8_0_deps,
        wheel = ":_wheel_pyproject-metadata@0.8.0",
    )

    _pyspark_3_5_2_deps = [
        ":py4j@0.10.9.7",
    ]

    native.alias(
        name = "_sdist_pyspark@3.5.2",
        actual = "@poetry_sdist_pyspark_3.5.2//file",
    )

    _pyspark_3_5_2_build_deps = [
        ":meson-python@0.16.0",
        ":setuptools@75.1.0",
        ":wheel@0.44.0",
    ]

    pycross_wheel_build(
        name = "_build_pyspark@3.5.2",
        sdist = ":_sdist_pyspark@3.5.2",
        target_environment = _target,
        deps = _pyspark_3_5_2_deps + _pyspark_3_5_2_build_deps,
        tags = ["manual"],
    )

    native.alias(
        name = "_wheel_pyspark@3.5.2",
        actual = ":_build_pyspark@3.5.2",
    )

    pycross_wheel_library(
        name = "pyspark@3.5.2",
        deps = _pyspark_3_5_2_deps,
        wheel = ":_wheel_pyspark@3.5.2",
    )

    native.alias(
        name = "_wheel_setuptools@75.1.0",
        actual = "@poetry_wheel_setuptools_75.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "setuptools@75.1.0",
        wheel = ":_wheel_setuptools@75.1.0",
    )

    native.alias(
        name = "_wheel_tomli@2.0.1",
        actual = "@poetry_wheel_tomli_2.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli@2.0.1",
        wheel = ":_wheel_tomli@2.0.1",
    )

    native.alias(
        name = "_wheel_wheel@0.44.0",
        actual = "@poetry_wheel_wheel_0.44.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel@0.44.0",
        wheel = ":_wheel_wheel@0.44.0",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        pypi_file,
        name = "poetry_sdist_numpy_2.1.1",
        package_name = "numpy",
        package_version = "2.1.1",
        filename = "numpy-2.1.1.tar.gz",
        sha256 = "d0cf7d55b1051387807405b3898efafa862997b4cba8aa5dbe657be794afeafd",
    )

    maybe(
        pypi_file,
        name = "poetry_sdist_pyspark_3.5.2",
        package_name = "pyspark",
        package_version = "3.5.2",
        filename = "pyspark-3.5.2.tar.gz",
        sha256 = "bbb36eba09fa24e86e0923d7e7a986041b90c714e11c6aa976f9791fe9edde5e",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_cowsay_6.1_py3_none_any",
        package_name = "cowsay",
        package_version = "6.1",
        filename = "cowsay-6.1-py3-none-any.whl",
        sha256 = "274b1e6fc1b966d53976333eb90ac94cb07a450a700b455af9fbdf882244b30a",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_meson_1.5.2_py3_none_any",
        package_name = "meson",
        package_version = "1.5.2",
        filename = "meson-1.5.2-py3-none-any.whl",
        sha256 = "77706e2368a00d789c097632ccf4fc39251fba56d03e1e1b262559a3c7a08f5b",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_meson_python_0.16.0_py3_none_any",
        package_name = "meson-python",
        package_version = "0.16.0",
        filename = "meson_python-0.16.0-py3-none-any.whl",
        sha256 = "842dc9f5dc29e55fc769ff1b6fe328412fe6c870220fc321060a1d2d395e69e8",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_packaging_24.1_py3_none_any",
        package_name = "packaging",
        package_version = "24.1",
        filename = "packaging-24.1-py3-none-any.whl",
        sha256 = "5b8f2217dbdbd2f7f384c41c628544e6d52f2d0f53c6d0c3ea61aa5d1d7ff124",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_py4j_0.10.9.7_py2.py3_none_any",
        package_name = "py4j",
        package_version = "0.10.9.7",
        filename = "py4j-0.10.9.7-py2.py3-none-any.whl",
        sha256 = "85defdfd2b2376eb3abf5ca6474b51ab7e0de341c75a02f46dc9b5976f5a5c1b",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_pyproject_metadata_0.8.0_py3_none_any",
        package_name = "pyproject-metadata",
        package_version = "0.8.0",
        filename = "pyproject_metadata-0.8.0-py3-none-any.whl",
        sha256 = "ad858d448e1d3a1fb408ac5bac9ea7743e7a8bbb472f2693aaa334d2db42f526",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_setuptools_75.1.0_py3_none_any",
        package_name = "setuptools",
        package_version = "75.1.0",
        filename = "setuptools-75.1.0-py3-none-any.whl",
        sha256 = "35ab7fd3bcd95e6b7fd704e4a1539513edad446c097797f2985e0e4b960772f2",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_tomli_2.0.1_py3_none_any",
        package_name = "tomli",
        package_version = "2.0.1",
        filename = "tomli-2.0.1-py3-none-any.whl",
        sha256 = "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc",
    )

    maybe(
        pypi_file,
        name = "poetry_wheel_wheel_0.44.0_py3_none_any",
        package_name = "wheel",
        package_version = "0.44.0",
        filename = "wheel-0.44.0-py3-none-any.whl",
        sha256 = "2376a90c98cc337d18623527a97c31797bd02bad0033d41547043a1cbfbe448f",
    )
