[tool.poetry]
name = "cowapp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.11"
cowsay = "^6.1"
numpy = "1.26.4"
pyspark = "^3.5.2"
setuptools = "68.2.2"
wheel = "0.41.3"
meson-python = "0.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
